export {
    AUTH_FAIL, AUTH_START,AUTH_SUCCESS,
    LOGIN_FAIL,LOGIN_START,LOGIN_SUCCESS,
    REGISTER_SCHOOL_FAIL,REGISTER_SCHOOL_START,REGISTER_SCHOOL_SUCCESS,
    GET_SCHOOLS_FAIL,GET_SCHOOLS_START,GET_SCHOOLS_SUCCESS,
    FORGOT_PASSWORD_FAIL,FORGOT_PASSWORD_START,FORGOT_PASSWORD_SUCCESS,
    CHANGE_PASSWORD_FAIL,CHANGE_PASSWORD_START,CHANGE_PASSWORD_SUCCESS,
    SIGNUP_FAIL,SIGNUP_START,SIGNUP_SUCCESS,
    ADD_TEACHER_START, ADD_TEACHER_SUCCESS, ADD_TEACHER_FAILURE,
    GET_ALL_SUBJECTS_START, GET_ALL_SUBJECTS_SUCCESS, GET_ALL_SUBJECTS_FAILURE,
    GET_ALL_STATES_START,GET_ALL_STATES_SUCCESS,GET_ALL_STATES_FAILURE,
    GET_ALL_CATEGORY_FAILURE,GET_ALL_CATEGORY_START,GET_ALL_CATEGORY_SUCCESS
    
} from './ActionTypes'

export {
    login,loginSuccess
} from './login'

export {
    auth,authSuccess
} from './auth'

export {
    forgot_Password, change_Password
} from './passwordChange'

export {
    signup
} from './signup'

export {
    addTeacher
} from './teacher'

export {
    getAllSubjects, getAllStates, getAllCategory
} from './resource'