export {
    USER_LOGIN, USER_CHANGE_PASSWORD, USER_FORGOT_PASSWORD, SIGNUP, BASEURL, CHECKTOKEN_VALIDITY,
    ADD_TEACHER, GET_ALL_SUBJECTS, GET_ALL_STATES, GET_DISTRICTS,GET_ALL_CATEGORY
    
} from './api'